baseURL = "https://blog.athulcyriac.xyz"
languageCode = "en-us"
title = "dayDreams ++"
copyright = "© Athul"
paginate=6
pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	favicon="/n1.png"
	mode="dark"
	useCDN=true
	subtitle = "Personal Blog of **Athul Cyriac Ajay**. Find more about me [here](https://athulcyriac.xyz)"
	description = "Because I daydream as incrementally"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/athul"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/athulcajay/"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/athul/"

[[menu.main]]
name = "RSS"
url = "/index.xml"
weight = 3

[[menu.main]]
name = "All Posts"
url = "/blog"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 1
