name: GitHub Pages Deploy

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Gatsby Publish
      run: yarn install&&yarn add gatsby-cli&&yarn upgrade&&node_modules/.bin/gatsby build --prefix-paths
      
    - name: deploy
      uses: peaceiris/actions-gh-pages@v1.1.0
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
    - name: notify
      uses: athul/statusoli@1.0.0
      if: always()
      with:
        chat: ${{ secrets.chat }} # user id or channel name secret
        token: ${{ secrets.token }} # token secret
        status: ${{ job.status }}
