name: GitHub Pages Deploy

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: enriikke/gatsby-gh-pages-action@v2
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-branch: gh-pages
        gatsby-args: --prefix-paths
