name: NoisyBoy

on: [push, pull_request, issues, issue_comment, watch]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Send Notification
      env:
          TELEGRAM_CHAT_ID: ${{ secrets.chat}}
          TELEGRAM_TOKEN: ${{secrets.token }}
          INPUT_STATUS: ${{ job.status }}
          STARGAZERS: ${{ github.event.repository.stargazers_count }}
          FORKERS: ${{ github.event.repository.forks_count }}
          IU_TITLE: ${{ github.event.issue.title }}
          IU_NUM: ${{ github.event.issue.number }}
          IU_ACTOR: ${{ github.event.issue.user.login }}
          IU_BODY: ${{ github.event.issue.body }}
          IU_COM: ${{github.event.comment.body}}
          PR_STATE: ${{ github.event.action }}
          PR_NUM: ${{ github.event.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}
        
      run: sh -c "$(curl -sL https://raw.githubusercontent.com/athul/autom/master/tg_gh_action_noti.sh)"
